/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MMGame.forms;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Random;
import javax.swing.JOptionPane;

import MMGame.model.Player;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
/**
 *
 * @author HP
 */
public class Level1 extends javax.swing.JFrame {

    //declare variables
    private double answer=0;
    double playerans;
    String ans;
    String mOperation, question;
    int no1, no2;
    int score ;
    int rounds = 0;
    
    private Player player;
   
    public Level1()
    {
        initComponents();
        this.setSize(700,750);
        this.setResizable(false); //does not allow user resize window form
    }
    /**
     * Creates new form Level1
     * @param p
     */
    public Level1(Player p) {
        
        initComponents();
        this.setSize(700,750);
        this.setResizable(false); //does not allow user resize window form
        //get player details
        this.player = p;
       // this.EasyQuestion(); //call method generate questions for game upon loading form
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        roundlabel = new javax.swing.JLabel();
        enterbtn = new javax.swing.JButton();
        quitbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ansTxtField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        questionlabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Level1");

        jPanel2.setBackground(new java.awt.Color(16, 44, 73));
        jPanel2.setToolTipText("Level 1");
        jPanel2.setLayout(null);

        roundlabel.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        roundlabel.setForeground(new java.awt.Color(255, 255, 255));
        roundlabel.setText("1");
        jPanel2.add(roundlabel);
        roundlabel.setBounds(400, 120, 50, 36);

        enterbtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        enterbtn.setText("Enter");
        enterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterbtnActionPerformed(evt);
            }
        });
        jPanel2.add(enterbtn);
        enterbtn.setBounds(400, 470, 120, 47);

        quitbtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        quitbtn.setText("Quit");
        quitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitbtnActionPerformed(evt);
            }
        });
        jPanel2.add(quitbtn);
        quitbtn.setBounds(540, 650, 110, 50);

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(537, 25, 128, 51);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MMGame/Images/play.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 530, 200, 200);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter your answer :");

        ansTxtField.setFont(new java.awt.Font("Segoe Print", 1, 22)); // NOI18N
        ansTxtField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(ansTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ansTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(180, 320, 350, 130);

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        questionlabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        questionlabel.setForeground(new java.awt.Color(255, 255, 255));
        questionlabel.setText("jLabel2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(questionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(220, 190, 270, 70);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Question");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(260, 120, 140, 36);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterbtnActionPerformed
       
    }//GEN-LAST:event_enterbtnActionPerformed

    private void quitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitbtnActionPerformed
         
    }//GEN-LAST:event_quitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level1().setVisible(true);
                //new Level1(player).setVisible(true);
                
            }
        });
    }
    
 
    //generate math question for easy level
    public double EasyQuestion() 
    {
        //call method to generate random integers 
        no1 = this.createNum(100); //set range to 100
        no2 = this.createNum(100); 
        
        //generate random 2 math operations
        //add, subtract
        int math = createNum (2);
        switch (math){
            case 0: 
                mOperation= "+";
                answer = no1 + no2;
                break;
                
           default: 
               mOperation = "-";
               answer = no1 - no2;
               break;
          
        }
        //display questions
        question =  (no1 + " " + mOperation + " " + no2 + " =  ?");
        questionlabel.setText(question);
        return this.answer;
    }
    
    public double InterMediateQuestion()
    {
        //call method to generate random integers 
        no1 = this.createNum(100); //set range to 100
        no2 = this.createNum(100); 
        
        //generate random 2 math operations
        //add, subtract
        int math = createNum (4);
        switch (math){
            case 0: 
                mOperation= "+";
                answer = no1 + no2;
                break;
                
           case 1:
                mOperation = "-";
                this.answer = this.no1 - this.no2;
                break;    
           case 2:
                mOperation = "*";
                this.answer = this.no1 * this.no2;
                break;
                
           default: 
               mOperation = "/";
               //prevent math error
               while (no2 == 0) {
                this.no2 = this.createNum(100);
                }
               this.answer = 1.0 * this.no1 /this.no2; //to make double num type
               break;
          
        }
        //display questions
        question =  (no1 + " " + mOperation + " " + no2 + " =  ?");
        questionlabel.setText(question);
        return this.answer;
    }
    
    public double AdvancedQuestion()
    {
        //call method to generate random integers 
        this.no1 = this.createNum(100); //set range to 100
        this.no2 = this.createNum(100); 
        
        //generate random 2 math operations
        int math = createNum (2);
        switch (math){
            case 0: 
                mOperation= "*";
                this.answer = this.no1 * this.no2 ;
                break;
                
           default: 
               mOperation = "/";
               //prevent math error
               while (no2 == 0 ) {
                this.no2 = this.createNum(100);
                }
               this.answer = 1.0 * this.no1 /this.no2; //to make double num type
               break;
          
        }
       //display questions
        question =  (no1 + " " + mOperation + " " + no2 + " =  ?");
        questionlabel.setText(question);
        return this.answer;
    }
    
    //generate random number for math integers
    public int createNum (int range)
    {
        //create instance class Random
        Random rand = new Random();
        int generate = rand.nextInt(range);
          
        return generate;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ansTxtField;
    private javax.swing.JButton enterbtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel questionlabel;
    private javax.swing.JButton quitbtn;
    private javax.swing.JLabel roundlabel;
    // End of variables declaration//GEN-END:variables

   //closing forms
    private void close() {
        WindowEvent winClosingEvent = new WindowEvent (this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    public JButton getEnterbtn() {
        return  enterbtn;
    }
    
    public JButton Quitbtn() {
        return  quitbtn;
    }
    public JTextField getplayerAnswer()
    {
        return ansTxtField;
    }
    
    public double getCorrectAnswer()
    {
        return answer;
    }
    public JLabel getRounds()
    {
        return roundlabel;
    }
}
