/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MMGame.forms;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

import MMGame.model.Player;
import javax.swing.JButton;
/**
 *
 * @author HP
 */
public class Levels extends javax.swing.JFrame {

    
    private Player player;
    /**
     * Creates new form Levels
     */
    public Levels() {
        initComponents();
        this.setSize(700,750);
        this.setResizable(false); //does not allow user resize window form
    }
    
    
    public Levels (Player p)
    {
        initComponents();
        this.setSize(700,750);
        this.setResizable(false); //does not allow user resize window form
        
        this.player = p;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        easybtn = new javax.swing.JButton();
        intermediatebtn = new javax.swing.JButton();
        advancedbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Levels");

        jPanel1.setBackground(new java.awt.Color(16, 44, 73));
        jPanel1.setLayout(null);

        easybtn.setText("Easy");
        easybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easybtnActionPerformed(evt);
            }
        });
        jPanel1.add(easybtn);
        easybtn.setBounds(250, 250, 214, 60);

        intermediatebtn.setText("Intermediate");
        intermediatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intermediatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(intermediatebtn);
        intermediatebtn.setBounds(250, 370, 214, 61);

        advancedbtn.setText("Advanced");
        advancedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedbtnActionPerformed(evt);
            }
        });
        jPanel1.add(advancedbtn);
        advancedbtn.setBounds(250, 490, 214, 63);

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn);
        backbtn.setBounds(560, 630, 107, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MMGame/Images/opps.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 40, 180, 169);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MMGame/Images/lev.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 70, 220, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
       
    }//GEN-LAST:event_backbtnActionPerformed

    private void easybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easybtnActionPerformed
        
       
    }//GEN-LAST:event_easybtnActionPerformed

    private void intermediatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intermediatebtnActionPerformed
       
    }//GEN-LAST:event_intermediatebtnActionPerformed

    private void advancedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedbtnActionPerformed
       
    }//GEN-LAST:event_advancedbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Levels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advancedbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton easybtn;
    private javax.swing.JButton intermediatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JButton getEasybtn() {
        return  easybtn;
    }
    public JButton getIntermediatebtn() {
        return  intermediatebtn;
    }
    public JButton getAdvancedbtn() {
        return  advancedbtn;
    }
    public JButton getBackbtn() {
        return  backbtn;
    }
    
}
